version: '3'

services:
  proxysql:
    image: "proxysql/proxysql:2.0.11"

    ports:
      - "16033:6033"
      - "16032:6032"

    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf

    depends_on:
      - mysql

  mysql:
    image: "mysql:5.7"

    ports:
      - "13306:3306"

    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

    environment:
      - MYSQL_ROOT_PASSWORD=root
